### ISSUE TITLE
!Clap doesn't support unicode or custom emotes

### ISSUE THREAD

**Issue by iitalics** [edward-shen/02#8]
Using the emote `:gay_pride_flag:` for `!clap` doesn't work, it doesn't recognize it as an emote

**Comment by edward-shen** [comment]
Confirmed regression, looks like this is affects all unicode and migrated emojis.

**Comment by edward-shen** [comment]
Specifically, the LGBT flag is a combination of multiple emojis, notably, the white flag emoji, a zero width joiner char, and the rainbow emoji. I suspect that the emoji lib dep doesn't properly support similar emojis, or has partial support.

**Comment by edward-shen** [comment]
Also looks likes custom emotes do work, but fails when there's a lot of simultaneous parsing. Might be because of the dispatching queue we use.

**Comment by edward-shen** [comment]
@erikuhlmann fixed in d3193845589bfc045bb5251943efdf75936e9642. Closing.
